# Question: Write a Python program to check if a number is even or odd.
# Date: 2025-01-16
# Question #14
# Generated by Gemini AI

def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"