# Question: Write a Python program to find the average of a list of numbers.
# Date: 2025-01-30
# Question #28
# Generated by Gemini AI

def find_average(numbers):
    if not numbers:
        return 0  # Handle empty list case
    return sum(numbers) / len(numbers)

# Get input from the user
number_str = input("Enter numbers separated by spaces: ")
numbers = [float(x) for x in number_str.split()]

# Calculate and print the average
average = find_average(numbers)
print("Average: ", average)