# Question: Write a Python program to reverse a string.
# Date: 2025-01-07
# Question #5
# Generated by Gemini AI

def reverse_string(s):
    return s[::-1]

#Example
string = "hello"
reversed_string = reverse_string(string)
print(f"The reversed string is: {reversed_string}")