# Question: Write a Python program to convert a list of strings to a list of integers.
# Date: 2025-01-21
# Question #19
# Generated by Gemini AI

def strings_to_integers(string_list):
  integer_list = []
  for string in string_list:
    try:
      integer = int(string)
      integer_list.append(integer)
    except ValueError:
      print(f"Skipping '{string}' as it cannot be converted to an integer.")
  return integer_list

# Get input from the user
input_strings = input("Enter a list of strings separated by spaces: ").split()

# Convert the list of strings to a list of integers
output_integers = strings_to_integers(input_strings)

# Print the list of integers
print("List of integers:", output_integers)
