# Question: Write a Python program to count vowels in a string.
# Date: 2025-01-08
# Question #6
# Generated by Gemini AI

def count_vowels(input_string):
    vowels = "aeiouAEIOU"
    vowel_count = 0
    for char in input_string:
        if char in vowels:
            vowel_count += 1
    return vowel_count

# Example usage
string = "Hello, World!"
number_of_vowels = count_vowels(string)
print(f"The number of vowels in the string is: {number_of_vowels}")