# Question: Write a Python program to find the common elements between two lists.
# Date: 2025-01-11
# Question #9
# Generated by Gemini AI

def common_elements(list1, list2):
    return list(set(list1) & set(list2))