# Question: Write a Python program to find the factorial of a number.
# Date: 2025-07-17
# Question #3
# Generated by Gemini AI

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)