# Question: Write a Python program to find the intersection of two lists.
# Date: 2025-01-24
# Question #22
# Generated by Gemini AI

def intersection(list1, list2):
    return list(set(list1) & set(list2))