# Question: Write a Python program to sum all elements of a list.
# Date: 2025-01-29
# Question #27
# Generated by Gemini AI

def sum_list(data):
  """Calculate the sum of elements in a list.

  Args:
    data: A list of numbers.

  Returns:
    The sum of all elements in the list. Returns 0 for an empty list.
  """
  if not data:
    return 0
  total = 0
  for number in data:
    total += number
  return total
