# Question: Write a Python program to find the factorial of a number.
# Date: 2024-06-24
# Generated by Gemini AI

def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)
num = int(input("Enter a number: "))
print("Factorial of", num, "is", factorial(num))