# Question: Write a Python program to convert a string to uppercase.
# Date: 2025-01-13
# Question #11
# Generated by Gemini AI

def convert_to_uppercase(input_string):
  return input_string.upper()

# Get input from the user
input_str = input("Enter a string: ")

# Convert the string to uppercase
uppercase_str = convert_to_uppercase(input_str)

# Print the uppercase string
print("Uppercase string:", uppercase_str)