# Question: Write a Python program to remove all white spaces from a string.
# Date: 2025-01-14
# Question #12
# Generated by Gemini AI

def remove_whitespace(input_string):
    return input_string.replace(" ", "")

# Example usage
string_with_spaces = " This string contains whitespace. "
string_without_spaces = remove_whitespace(string_with_spaces)
print(f"Original string: {string_with_spaces}")
print(f"String without spaces: {string_without_spaces}")