# Question: Write a Python program to find the sum of digits of a number.
# Date: 2025-01-27
# Question #25
# Generated by Gemini AI

def sum_digits(number):
  sum = 0
  while number > 0:
    digit = number % 10
    sum += digit
    number //= 10
  return sum

number = int(input("Enter a number: "))
result = sum_digits(number)
print("Sum of digits:", result)