# Question: Write a Python program to find the LCM of two numbers.
# Date: 2025-01-20
# Question #18
# Generated by Gemini AI

def find_lcm(num1, num2):
    """Find the LCM of two numbers using the GCD."""

    # Find the GCD using the Euclidean algorithm
    def find_gcd(a, b):
        while(b):
            a, b = b, a % b
        return a

    # LCM(a, b) = (a * b) / GCD(a, b)
    gcd = find_gcd(num1, num2)
    lcm = (num1 * num2) // gcd
    return lcm

# Get input from the user
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Find and print the LCM
lcm = find_lcm(num1, num2)
print("The LCM of", num1, "and", num2, "is:", lcm)
