# Question: Write a Python program to find the largest number in a list.
# Date: 2025-01-09
# Question #7
# Generated by Gemini AI

def findLargest(numbers):
    if not numbers:
        return None  # Handle empty list case
    largest = numbers[0]
    for number in numbers:
        if number > largest:
            largest = number
    return largest

# Example usage:
numberList = [10, 5, 20, 15, 30, 25]
largestNumber = findLargest(numberList)
print(f"The largest number in the list is: {largestNumber}")

numberList = []
largestNumber = findLargest(numberList)
print(f"The largest number in the list is: {largestNumber}")