# Question: Write a Python program to flatten a list of lists.
# Date: 2025-01-26
# Question #24
# Generated by Gemini AI

def flatten_list(list_of_lists):
  """Flatten a list of lists into a single list.

  Args:
    list_of_lists: A list containing other lists.

  Returns:
    A new list containing all the elements from the nested lists.
  """
  flat_list = []
  for sublist in list_of_lists:
    for item in sublist:
      flat_list.append(item)
  return flat_list

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_list = flatten_list(nested_list)
print(f"Original list: {nested_list}")
print(f"Flattened list: {flattened_list}")