# Question: Write a Python program to count vowels in a string.
# Date: 2025-07-20
# Question #6
# Generated by Gemini AI

def count_vowels(input_str):
    vowels = "aeiouAEIOU"
    count = 0
    for char in input_str:
        if char in vowels:
            count += 1
    return count

input_string = input("Enter a string: ")
result = count_vowels(input_string)
print("Number of vowels:", result)